---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: postgresql
data:
  postgresql.conf: |
    # Add your custom postgresql.conf configuration here
    #     # Example:
    #         max_connections = 100
    #             shared_buffers = 128MB
    #
    data_directory = '/var/lib/postgresql/data'
