apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: postgresql
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13.11
          env:
            - name: POSTGRES_USER
              value: gitlab
            - name: POSTGRES_PASSWORD
              value: sonar
            - name: POSTGRES_DB
              value: sonar
            - name: POSTGRES_USER_GITLAB  # Add a new environment variable for GitLab user
              value: gitlab               # GitLab username
            - name: POSTGRES_PASSWORD_GITLAB  # Add a new environment variable for GitLab user's password
              value: LetMeIn9                # GitLab user's password
            - name: POSTGRES_DB_GITLAB     # Add a new environment variable for GitLab database
              value: gitlabhq_production   # GitLab database name
          ports:
            - containerPort: 5432
          resources:
            limits:
              memory: 2Gi
              cpu: 4
            requests:
              memory: 1Gi
              cpu: 1
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: config
              mountPath: /docker-entrypoint-initdb.d/postgresql.conf
              subPath: postgresql.conf
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
        - name: config
          configMap:
            name: postgres-config

